name: Daily Auto Commit

on:
  schedule:
    - cron: '2 14 * * *' # Runs daily at 10:00 AM IST

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clear previous data and Add new data
        run: |
          # Clear the contents of daily-log.txt before adding new data
          > daily-log.txt
          echo "Updated on $(date)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "ujjwaldethe"
          git config --global user.email "ujwaldethe518@gmail.com"
          git add .
          git commit -m "$(date)"
          git push
